// Sistema de temas para la aplicación

export const THEMES = {
  dark: {
    id: 'dark',
    name: 'Oscuro Clásico',
    emoji: '🌙',
    colors: {
      primary: '#6C63FF',
      secondary: '#FF6584',
      accent: '#22d3ee',
      background: '#0f0f1e',
      surface: '#1a1a2e',
      surfaceLight: '#252541',
      text: '#ffffff',
      textSecondary: '#888888',
      textTertiary: '#666666',
      border: '#333333',
      success: '#4CAF50',
      warning: '#FFC107',
      error: '#F44336',
      cardBg: '#1a1a2e',
    },
  },
  
  light: {
    id: 'light',
    name: 'Claro',
    emoji: '☀️',
    colors: {
      primary: '#6C63FF',
      secondary: '#FF6584',
      accent: '#22d3ee',
      background: '#f5f5f5',
      surface: '#ffffff',
      surfaceLight: '#fafafa',
      text: '#1a1a1a',
      textSecondary: '#666666',
      textTertiary: '#999999',
      border: '#e0e0e0',
      success: '#4CAF50',
      warning: '#FFC107',
      error: '#F44336',
      cardBg: '#ffffff',
    },
  },
  
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    emoji: '🌆',
    colors: {
      primary: '#00ffff',
      secondary: '#ff00ff',
      accent: '#ffff00',
      background: '#0a0a1a',
      surface: '#1a0a2e',
      surfaceLight: '#2a1a3e',
      text: '#00ffff',
      textSecondary: '#ff00ff',
      textTertiary: '#8800ff',
      border: '#ff00ff',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0066',
      cardBg: '#1a0a2e',
    },
  },
  
  ocean: {
    id: 'ocean',
    name: 'Océano Profundo',
    emoji: '🌊',
    colors: {
      primary: '#00d4ff',
      secondary: '#0095ff',
      accent: '#00fff7',
      background: '#001a2e',
      surface: '#002642',
      surfaceLight: '#003356',
      text: '#ffffff',
      textSecondary: '#7dd3fc',
      textTertiary: '#0891b2',
      border: '#0284c7',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      cardBg: '#002642',
    },
  },
  
  forest: {
    id: 'forest',
    name: 'Bosque Místico',
    emoji: '🌲',
    colors: {
      primary: '#10b981',
      secondary: '#84cc16',
      accent: '#facc15',
      background: '#0f1e0f',
      surface: '#1a2e1a',
      surfaceLight: '#243e24',
      text: '#ffffff',
      textSecondary: '#86efac',
      textTertiary: '#4ade80',
      border: '#16a34a',
      success: '#22c55e',
      warning: '#eab308',
      error: '#dc2626',
      cardBg: '#1a2e1a',
    },
  },
  
  sunset: {
    id: 'sunset',
    name: 'Atardecer Gamer',
    emoji: '🌅',
    colors: {
      primary: '#f97316',
      secondary: '#ec4899',
      accent: '#fbbf24',
      background: '#1a0f0a',
      surface: '#2e1a1a',
      surfaceLight: '#3e2424',
      text: '#ffffff',
      textSecondary: '#fda4af',
      textTertiary: '#fb923c',
      border: '#dc2626',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#ef4444',
      cardBg: '#2e1a1a',
    },
  },
  
  purple: {
    id: 'purple',
    name: 'Púrpura Real',
    emoji: '👾',
    colors: {
      primary: '#a855f7',
      secondary: '#ec4899',
      accent: '#f59e0b',
      background: '#1e0a2e',
      surface: '#2e1a3e',
      surfaceLight: '#3e2a4e',
      text: '#ffffff',
      textSecondary: '#d8b4fe',
      textTertiary: '#c084fc',
      border: '#9333ea',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      cardBg: '#2e1a3e',
    },
  },
  
  matrix: {
    id: 'matrix',
    name: 'Matrix',
    emoji: '💻',
    colors: {
      primary: '#00ff41',
      secondary: '#00ff41',
      accent: '#39ff14',
      background: '#000000',
      surface: '#0a1a0a',
      surfaceLight: '#1a2a1a',
      text: '#00ff41',
      textSecondary: '#00cc33',
      textTertiary: '#009922',
      border: '#00ff41',
      success: '#00ff41',
      warning: '#ffff00',
      error: '#ff0000',
      cardBg: '#0a1a0a',
    },
  },
  
  blood: {
    id: 'blood',
    name: 'Sangre y Acero',
    emoji: '⚔️',
    colors: {
      primary: '#dc2626',
      secondary: '#7f1d1d',
      accent: '#fb923c',
      background: '#1a0a0a',
      surface: '#2a1a1a',
      surfaceLight: '#3a2424',
      text: '#ffffff',
      textSecondary: '#fca5a5',
      textTertiary: '#f87171',
      border: '#991b1b',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#dc2626',
      cardBg: '#2a1a1a',
    },
  },
};

export const getThemeColors = (themeId) => {
  return THEMES[themeId]?.colors || THEMES.dark.colors;
};

export const getAllThemes = () => {
  return Object.values(THEMES);
};
